const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('accela', {
  newTab: (url) => ipcRenderer.invoke('new-tab', url),
  closeTab: (tabId) => ipcRenderer.invoke('close-tab', tabId),
  switchTab: (tabId) => ipcRenderer.invoke('switch-tab', tabId),
  navigate: (tabId, url) => ipcRenderer.invoke('navigate', { tabId, url }),
  goBack: () => ipcRenderer.invoke('go-back'),
  goForward: () => ipcRenderer.invoke('go-forward'),
  reload: () => ipcRenderer.invoke('reload'),
  getTabs: () => ipcRenderer.invoke('get-tabs'),
  moveTab: (draggedId, targetId) => ipcRenderer.invoke('move-tab', { draggedId, targetId }),
  debugTabs: () => ipcRenderer.invoke('debug-tabs'),
  onTabCreated: (cb) => ipcRenderer.on('tab-created', (e, d) => cb(d)),
  onTabClosed: (cb) => ipcRenderer.on('tab-closed', (e, d) => cb(d)),
  onTabActivated: (cb) => ipcRenderer.on('tab-activated', (e, d) => cb(d)),
  onTabUpdated: (cb) => ipcRenderer.on('tab-updated', (e, d) => cb(d)),
  onFocusAddressBar: (cb) => ipcRenderer.on('focus-address-bar', () => cb()),
  getBookmarks: () => ipcRenderer.invoke('get-bookmarks'),
  getHistory: () => ipcRenderer.invoke('get-history'),
  setSidebarWidth: (w) => ipcRenderer.invoke('set-sidebar-width', w),
  setPanelWidth: (w) => ipcRenderer.invoke('set-panel-width', w),
  addBookmark: (title, url) => ipcRenderer.invoke('add-bookmark', { title, url }),
  removeBookmark: (url) => ipcRenderer.invoke('remove-bookmark', url),
  toggleDevTools: () => ipcRenderer.invoke('toggle-devtools'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSearchEngine: (id) => ipcRenderer.invoke('set-search-engine', id),
  getSiteInfo: () => ipcRenderer.invoke('get-site-info'),
  onPageLoading: (cb) => ipcRenderer.on('page-loading', (e, loading) => cb(loading)),
  onTabsChanged: (cb) => ipcRenderer.on('tabs-changed', (e, tabs) => cb(tabs)),
  reorderTab: (fromId, toId) => ipcRenderer.invoke('reorder-tab', { fromId, toId }),
  tileTabs: (leftId, rightId) => ipcRenderer.invoke('tile-tabs', { leftId, rightId }),
  untileTabs: () => ipcRenderer.invoke('untile-tabs'),
  toggleVerticalTabs: () => ipcRenderer.invoke('toggle-vertical-tabs'),
  getVerticalTabs: () => ipcRenderer.invoke('get-vertical-tabs'),
  onTilingChanged: (cb) => ipcRenderer.on('tiling-changed', (e, d) => cb(d)),
  onVerticalChanged: (cb) => ipcRenderer.on('vertical-changed', (e, v) => cb(v)),
  openSettings: () => ipcRenderer.invoke('open-settings'),
  showBlackiceMenu: () => ipcRenderer.invoke('show-blackice-menu'),
  showTabMenu: (tabId, x, y) => ipcRenderer.invoke('show-tab-menu', { tabId, x, y }),
  pinTab: (tabId) => ipcRenderer.invoke('pin-tab', tabId),
  unpinTab: (tabId) => ipcRenderer.invoke('unpin-tab', tabId),
});
